### PR TITLE
Change the values of ingest/callback status

### LINKED ISSUE #3074: Changes to ingest/callback status
The current values for `Status` on `Ingest` and `Callback` are:

- `initialised`, `processing`, `success`, `failure`

To improve consistency of language, these should be changed to:

- `accepted`, `processing`, `succeeded`, `failed`

### PR DESCRIPTION
**Pull request by alexwlchan**
Resolves #3074.

### CODE REVIEW

File: archive/common/src/main/scala/uk/ac/wellcome/platform/archive/common/progress/models/Progress.scala [hunk 1]
```diff
@@ -19,25 +19,25 @@ case class Progress(id: UUID,
...
   private val processingString = "processing"
-  private val successString = "success"
-  private val failureString = "failure"
+  private val succeededString = "succeeded"
+  private val failedString = "failed"
 
-  case object Initialised extends Status {
-    override def toString: String = initialisedString
+  case object Accepted extends Status {
+    override def toString: String = acceptedString
```
Comment (mklander) [inline archive/common/src/main/scala/uk/ac/wellcome/platform/archive/common/progress/models/Progress.scala]: Will this break when deserialising existing stored progress?  As it is progress maybe that's fine...

Comment (alexwlchan) [reply archive/common/src/main/scala/uk/ac/wellcome/platform/archive/common/progress/models/Progress.scala]: Yes.

I thought the database was only test data, so that was safe, but perhaps I've missed something?

Comment (mklander) [reply archive/common/src/main/scala/uk/ac/wellcome/platform/archive/common/progress/models/Progress.scala]: I think then something to be aware of.
