### PR TITLE
Return a 404 error if you look up a non-existent index

### LINKED ISSUE #965: Selecting the wrong index should be an HTTP 404 error
Right now, if you hit https://api.wellcomecollection.org/catalogue/v0/works?_index=foo you can search an alternative index.

This is useful when we’re doing reindexing, and we’ll probably use it more as we start tweaking the search weightings.

But if you try it and the index doesn’t exist, you get a 500 error, and an alarm pops up in Slack. Sadness! We should make this a 404 error instead.

One note, however: we’re using the non-existence of an index to test that 500s return correctly, because it’s a reliable source of errors. What can we use instead for those tests?

### PR DESCRIPTION
**Pull request by alexwlchan**
### What is this PR trying to achieve?

In the title. Which is really a way to stop alarms in our Slack channel for what’s a pretty benign error. Plus some tidying the internal logic of the ExceptionMapper, which is still a bit crappy but now in a different way. (A pox on the Elasticsearch SDK for not returning proper error types!)

Resolves #965.

### Who is this change for?

Me, because I’m bored of investigating those alarms.

oh also i guess users who want helpful error messages \*sigh*

### Have the following been considered/are they needed?

- [ ] Deployed new versions

### CODE REVIEW

File: api/src/main/scala/uk/ac/wellcome/platform/api/finatra/exceptions/ElasticsearchResponseExceptionMapper.scala [hunk 1]
```diff
@@ -29,52 +29,91 @@ class ElasticsearchResponseExceptionMapper @Inject()(
     error(
       s"Sending HTTP 400 from ElasticsearchResponseExceptionMapper ($message)",
       exception)
-    DisplayError(Error(variant = "http-400", description = Some(message)))
+    DisplayError(Error(variant = s"http-400", description = Some(message)))
```
Comment (alexwlchan) [inline api/src/main/scala/uk/ac/wellcome/platform/api/finatra/exceptions/ElasticsearchResponseExceptionMapper.scala]: s-strings here are unnecessary, and an artefact of an earlier version of this code

File: api/src/main/scala/uk/ac/wellcome/platform/api/finatra/exceptions/ElasticsearchResponseExceptionMapper.scala [hunk 2]
```diff
@@ -29,52 +29,91 @@ class ElasticsearchResponseExceptionMapper @Inject()(
...
+    val exceptionData = mapper.readTree(jsonDocument)
+
+    val esError = exceptionData.get("error")
+    val esErrorType = esError
+      .get("type")
+      .asText
+
+    esErrorType match {
+      // This occurs if the user requests a non-existent index as ?_index=foo.
+      // We return this as a 404 error to the user.
```
Comment (alexwlchan) [inline api/src/main/scala/uk/ac/wellcome/platform/api/finatra/exceptions/ElasticsearchResponseExceptionMapper.scala]: this line is redundant

File: api/src/main/scala/uk/ac/wellcome/platform/api/finatra/exceptions/ElasticsearchResponseExceptionMapper.scala [hunk 3]
```diff
@@ -29,52 +29,91 @@ class ElasticsearchResponseExceptionMapper @Inject()(
...
+      case "index_not_found_exception" => {
+        val index = esError
+          .get("index")
+          .asText
+        notFound(s"There is no index $index", exception)
+      }
+
+      // This may occur if the user requests an overly large page of results.
+      // We return this as a 400 error to the user.
```
Comment (alexwlchan) [inline api/src/main/scala/uk/ac/wellcome/platform/api/finatra/exceptions/ElasticsearchResponseExceptionMapper.scala]: and this, just needs a comment about the error type
