### PR TITLE
Strip extra punctuation in identifiers for Sierra contributors

### LINKED ISSUE #2015: Works are landing on the transformer DLQ
The following nine works are unexpectedly on the transformer DLQ:

```
3017492
3017502
3017504
3017507
3020991
3020992
3025126
3025132
3025707
```

### PR DESCRIPTION
**Pull request by alexwlchan**
### What is this PR trying to achieve?

Make sure we can handle seeing full stops and commas in identifiers for Sierra contributors. Resolves #2015.

### Who is this change for?

🍏 🇬🇷

### CODE REVIEW

File: catalogue_pipeline/transformer/src/test/scala/uk/ac/wellcome/transformer/transformers/sierra/SierraContributorsTest.scala [hunk 1]
```diff
@@ -361,13 +361,17 @@ class SierraContributorsTest extends FunSpec with Matchers {
...
+    it(
+      "combines identifiers with inconsistent spacing/punctuation from subfield $$0") {
       val name = "Wanda the watercress"
       val lcshCodeCanonical = "lcsh2055034"
       val lcshCode1 = "lcsh 2055034"
       val lcshCode2 = "  lcsh2055034 "
       val lcshCode3 = " lc sh 2055034"
 
+      // Based on an example from a real record; see Sierra b3017492.
+      val lcshCode4 = "lcsh 2055034.,"
```
Comment (alicefuzier) [inline catalogue_pipeline/transformer/src/test/scala/uk/ac/wellcome/transformer/transformers/sierra/SierraContributorsTest.scala]: 🤦‍♀️ 😂
